baseURL = "/"
languageCode = "en-us"
title = "Pathfinder - Kingmaker"
summaryLength = 30
disableKinds = [ "taxonomy", "term" ]

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[module.hugoVersion]
extended = true
min = "0.100.0"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "assets"
target = "assets"
